=== Volkr-Both/AIGUI/aigui/redist/conf/aigui.dtd
<!ELEMENT aigui (Functions,Toolbar)>
<!ATTLIST aigui
 date CDATA #IMPLIED
>

<!ELEMENT Functions (Function)*>

<!ELEMENT Function (Options|Properties|Notebook)*>
<!ATTLIST Function 
 id   ID     #REQUIRED
 succ CDATA  #IMPLIED
>

<!ELEMENT Properties (Entry)*>
<!ATTLIST Properties 
 id CDATA  #REQUIRED
>
<!ELEMENT Entry (#PCDATA)>
<!ATTLIST Entry
 key CDATA #REQUIRED
>

<!ELEMENT Options (Option|FileParam)*>
<!ELEMENT Option (Value)*>
<!ELEMENT Value (#PCDATA)>

<!ELEMENT FileParam (FileFilter)*>
<!ATTLIST FileParam
  id          CDATA                            #REQUIRED
  label       CDATA                            #REQUIRED
  tooltip     CDATA                            #IMPLIED
  option      CDATA                            #IMPLIED
>

<!ELEMENT FileFilter (#PCDATA)>
<!ATTLIST FileFilter
  desc       CDATA                             #REQUIRED
  ext        CDATA                             #REQUIRED
  selector   CDATA                             #IMPLIED
>

<!ATTLIST Options
  id       CDATA                             #REQUIRED
  title    CDATA                             #REQUIRED
  columns  CDATA                             #IMPLIED
  tooltip  CDATA                             #IMPLIED
  compound (false | true)                    'false'
>
  
<!ATTLIST Option
  id       CDATA                             #REQUIRED
  default  CDATA                             #IMPLIED
  init     CDATA                             #IMPLIED
  type     CDATA                             #REQUIRED
  enabled  (false | true)                    'true'       
  fill     (none  | both)                    'both'
  tooltip  CDATA                             #REQUIRED
>
<!--
      '+' not allowed in option list
      type     (enum | text | text+enum )         #REQUIRED
  -->
<!ELEMENT Notebook (Command | Variable)*>
<!ATTLIST Command
  action     CDATA                    'eval'
>
<!ELEMENT Command (#PCDATA)>
<!ELEMENT Variable (#PCDATA)>
<!ATTLIST Variable
  id       CDATA                             #REQUIRED
>
<!ELEMENT Toolbar (Button)*>
<!ELEMENT Button (#PCDATA)>

=== Volkr-Both/AIGUI/aigui/conf/aiguiconf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aigui SYSTEM "aigui.dtd">
<aigui date="2007-09-13 15:49:00">
	<!--Configuration file for aigui
author: Volker Boos
volker.boos@imms.de
-->
	<Functions>
		<Function id="Initialization" succ="ReadNetlist TestFunction">
			<Options id="main" title="Initialisation commands">
				<Option id="Commands" type="text" tooltip="valid notebook commands">
					<Value>&lt;&lt;AnalogInsydes`</Value>
					<!--"<<AnalogInsydes`IFX`"-->
					<Value>Off[General::spell, General::spell1];</Value>
					<Value>SetOptions[AnalogInsydes, ModelLibrary -&gt; {"FullModels`"}];</Value>
					<Value>SetOptions[BodePlot,PlotPoints -&gt; 200,PlotRange-&gt; All];</Value>
					<Value>SetOptions[LinearSolve, Method -&gt; Multifrontal];</Value>
					<!--<Value>SetOptions[AnalogInsydes, ModelLibrary -&gt; {"IFXFullMOSFETModels`", "FullModels`"}]</Value>-->
				</Option>
			</Options>
			<Options id="global" title="Global Options">
				<Option id="InstanceNameSeparator" default="Inherited[AnalogInsydes]" tooltip="separator string for name components" type="text"/>
				<Option id="LibraryPath" default="Inherited[AnalogInsydes]" tooltip="search path for device model libraries" type="text"/>
				<Option id="ModelLibrary" default="Inherited[AnalogInsydes]" tooltip="default device model library" type="text"/>
				<Option id="Protocol" default="StatusLine" tooltip="amount and location of protocol" type="text+enum">
					<Value>All</Value>
					<Value>None</Value>
					<Value>Notebook</Value>
					<Value>StatusLine</Value>
				</Option>
				<Option id="Simulator" default="&quot;AnalogInsydes&quot;" tooltip="default simulator" type="text"/>
				<Option id="UseExternals" default="True" tooltip="use external MathLink modules" type="enum">
					<Value>False</Value>
					<Value>True</Value>
				</Option>
			</Options>
		</Function>
		<Function id="ReadNetlist" succ="CircuitEquations TransientEquations Statistics">
			<Options id="main" title="Main Options">
				<Option id="Simulator" default="Inherited[AnalogInsydes]" tooltip="Netlist format" type="enum" enabled="false" fill="none">
					<Value>"AnalogArtist"</Value>
					<Value>"AnalogInsydes"</Value>
					<Value>"Eldo"</Value>
					<Value>"PSpice"</Value>
					<Value>"Saber"</Value>
					<Value>"SpectreS"</Value>
					<Value>"Titan"</Value>
				</Option>
				<FileParam  id="NetlistFile" label="Netlist file:" option="Simulator" tooltip="file that contains the netlist">
					<FileFilter selector="&quot;AnalogInsydes&quot;" desc="AnalogInsydes (*.m)"  ext="m" />
					<FileFilter selector="&quot;AnalogArtist&quot;"  desc="Analog Artist (*.ai;*.ain)" ext="ai|ain"/>
					<FileFilter selector="&quot;PSpice&quot;"        desc="PSpice Files (*.cir)" ext="cir"/>
					<FileFilter selector="&quot;Titan&quot;"         desc="Titan Files (*.in.tit)" ext="in.tit"/>
					<FileFilter selector="&quot;Eldo&quot;"          desc="Eldo Files (*.cir)" ext="cir"/>
				</FileParam>
				<FileParam  id="OppointFile" label="Op-point file:" option="Simulator" tooltip="file that contains the simulated operation point data">
					<FileFilter selector="&quot;AnalogInsydes&quot;" desc="AnalogInsydes (*.m)"  ext="m" />
					<FileFilter selector="&quot;AnalogArtist&quot;"  desc="(dcOpInfo.info included in netlist)" ext=""/>
					<FileFilter selector="&quot;PSpice&quot;"        desc="PSpice Out Files (*.out)" ext="out"/>
					<FileFilter selector="&quot;Titan&quot;"         desc="Titan Out Files (*.pr.tit)" ext="pr.tit"/>
					<FileFilter selector="&quot;Eldo&quot;"          desc="Eldo Out Files (*.*)" ext="*"/>
				</FileParam>
			</Options>
			<Options id="base" title="Basic Options">
				<FileParam id="SchematicFile" label="Schematic:" tooltip="Schematic file">
					<FileFilter desc="DXF files (*.dxf)" ext="dxf" />
					<FileFilter desc="Notebook files (*.m)" ext="m" />
				</FileParam>
			</Options>
			<Options id="adv" columns="2" title="Advanced Options">
				<Option id="CharacterMapping" default="{&quot;_&quot; -&gt; &quot;$&quot;}" tooltip="List of Rules: {String -&gt; String, ...}" type="text"/>
				<Option id="InstanceNameSeparator" default="Inherited[AnalogInsydes]" tooltip="String that evaluates to a Symbol" type="text"/>
				<Option id="KeepPrefix" default="True" tooltip="{}" type="enum">
					<Value>False</Value>
					<Value>True</Value>
				</Option>
				<Option id="LevelSeparator" default="&quot;/&quot;" tooltip="String" type="text"/>
				<Option id="LibraryPath" default="{&quot;.&quot;}" tooltip="String, List of Strings" type="text"/>
				<Option id="ParseOnly" default="False" tooltip="{}" type="enum">
					<Value>False</Value>
					<Value>True</Value>
				</Option>
				<Option id="Protocol" default="Inherited[AnalogInsydes]" tooltip="List of valid Symbols" type="text+enum">
					<Value>Inherited[AnalogInsydes]</Value>
					<Value>All</Value>
					<Value>None</Value>
					<Value>Notebook</Value>
					<Value>StatusLine</Value>
				</Option>
				<Option id="UserPDKMap" default="None" tooltip="Symbol or Function" type="text"/>
			</Options>
		</Function><Function id="CircuitEquations" succ="ReadSimulationData ComplexityEstimation Statistics Solve CompressMatrixEquation PolesAndZerosByQZ ApproximateDeterminant RootLocusByQZ CharacteristicPolynomial">
			<Notebook>
				<Variable id="MatrixEquations">equations</Variable>
			</Notebook>
			<Options id="main" title="Main Options">
			</Options>
			<Options id="modlib" title="Model Library" tooltip="model library options">
				<Option id="ModelLibrary" default="Inherited[AnalogInsydes]" tooltip="model libraries used" type="enum" enabled="false">
					<Value>Inherited[AnalogInsydes]</Value>
					<Value>"FullModels`"</Value>
					<Value>"SimplifiedModels`"</Value>
					<Value>"BasicModels`"</Value>
					<Value>"IFXFullMOSFETModels`"</Value>
					<Value>"IFXSimplifiedMOSFETModels`"</Value>
					<Value>"IFXBasicMOSFETModels`"</Value>
				</Option>
				<Option id="DefaultSelector" default="Automatic" tooltip="Symbol or String" type="text+enum">
					<Value>Automatic</Value>
				</Option>
				<Option id="LibraryPath" default="Inherited[AnalogInsydes]" tooltip="String&quot;, &quot;List of Strings" type="text" />
			</Options>
			<Options id="adv1" columns="2" title="Analysis Mode" tooltip="Analysis Mode">
				<Option id="AnalysisMode" default="" init="AC" tooltip="circuit analysis mode (default: AC)" type="enum">
					<Value>AC</Value>
					<Value>Transient</Value>
				</Option>
				<Option id="FrequencyVariable" default="s" tooltip="Symbol for complex Laplace frequency" type="text" />
				<Option id="IndependentVariable" default="Automatic" tooltip="Symbol" type="text+enum">
					<Value>Automatic</Value>
				</Option>
				<Option id="InitialGuess" default="Automatic" tooltip="List of Rules: {Symbol -&gt; Real number, ...}" type="text+enum">
					<Value>Automatic</Value>
				</Option>
				<Option id="InitialTime" default="0" tooltip="initial time for transisent analysis (real number)" type="text" />
				<Option id="TimeVariable" default="t" tooltip="Symbol for time in transient analysis" type="text" />
			</Options>
			<Options id="adv2" columns="2" title="Equation Formulation" tooltip="Equation Formulation">
				<Option id="ElementValues" default="Value" init="Symbolic" tooltip="numeric or symbolic equations" type="enum" enabled="false">
					<Value>Symbolic</Value>
					<Value>Value</Value>
				</Option>
				<Option id="Formulation" default="ModifiedNodal" tooltip="circuit analysis formulation" type="enum" enabled="false">
					<Value>ExtendedTableau</Value>
					<Value>ModifiedNodal</Value>
					<Value>SparseTableau</Value>
				</Option>
				<Option id="ConvertImmittances" default="True" tooltip="convert impedances to admittances" type="enum">
					<Value>False</Value>
					<Value>True</Value>
				</Option>
				<Option id="InitialConditions" default="None" tooltip="initial conditions for dynamics" type="enum">
					<Value>All</Value>
					<Value>Automatic</Value>
					<Value>None</Value>
				</Option>
				<Option id="MatrixEquation" default="True" tooltip="AC equations as matrix" type="enum">
					<Value>False</Value>
					<Value>True</Value>
				</Option>
				<Option id="Symbolic" default="All" tooltip="List of Rules: {String -&gt; Symbol or String, ...}&quot;, &quot;List of Rules: {List of Strings -&gt; List of Symbols or Strings, ...}" type="text+enum">
					<Value>All</Value>
					<Value>None</Value>
				</Option>
				<Option id="Value" default="None" tooltip="List of Rules: {String -&gt; Symbol or String, ...}&quot;, &quot;List of Rules: {List of Strings -&gt; List of Symbols or Strings, ...}" type="text+enum">
					<Value>All</Value>
					<Value>None</Value>
				</Option>
			</Options>
			<Options id="adv3" columns="2" title="Naming Conventions" tooltip="Naming Conventions">
				<Option id="BranchCurrentPrefix" default="&quot;I$&quot;" tooltip="String that evaluates to a Symbol" type="text" />
				<Option id="BranchVoltagePrefix" default="&quot;V$&quot;" tooltip="String that evaluates to a Symbol" type="text" />
				<Option id="ControllingCurrentPrefix" default="&quot;IC$&quot;" tooltip="String that evaluates to a Symbol" type="text" />
				<Option id="ControllingVoltagePrefix" default="&quot;VC$&quot;" tooltip="String that evaluates to a Symbol" type="text" />
				<Option id="InstanceNameSeparator" default="Inherited[AnalogInsydes]" tooltip="String that evaluates to a Symbol" type="text" />
				<Option id="NodeVoltagePrefix" default="&quot;V$&quot;" tooltip="String that evaluates to a Symbol" type="text" />
			</Options>
			<Options id="adv4" columns="2" title="Other" tooltip="other advanced options">
				<Option id="Protocol" default="Inherited[AnalogInsydes]" tooltip="List of valid Symbols" type="text+enum" enabled="false">
					<Value>All</Value>
